### ISSUE TITLE
Would it be possible to add an option to dump a given binary file?

### ISSUE THREAD

**Issue by ThePantsThief** [KJCracks/Clutch#134]
I have specific arch slices of IPAs I want decrypted.

**Comment by Tatsh** [comment]
Not at this time. I think Clutch 1 did that. You could try swapping binaries with an app you have installed.

If you are just class-dumping, classdump-dyld will take a binary as input: `classdump-dyld -o outdir /usr/libexec/backboardd` . But it may not work for a random binary since dyld depends on `dyld_shared_cache` IIRC.

Do you have the FairPlay metadata? You cannot dump a binary without passing through `fairplayd`.

**Comment by ttwj** [comment]
We could previously extract the SC_Info folder with the binary and decrypt it, but iOS9+ only allows the binary to be launched from a proper application container. To achieve a similar effect, you could possibly "thin" the IPA by only keeping the binary, Info.plist and SC_Info, and just dump it as usual.
