### ISSUE TITLE
Change license to a more permissive one like MIT or Apache

### ISSUE THREAD

**Issue by sumukhanand** [KJCracks/Clutch#80]
We'd love to use Clutch, and contribute back any changes and improvements we make, but for some annoying bureaucratic reasons, we need the license changed to MIT or Apache before we can do so.

Is there any chance you guys can change the Clutch license from AGPL to either of those licenses?

Thanks!

**Comment by Tatsh** [comment]
Since I have contributed in some ways to the project, I ask: why? Why can't you release your code? Why can't you make PRs here of whatever changes you plan on making?

If you are building some kind of auto-cracking tool (especially commercial) that will be 'better' if the code is linked and that you do not wish to release the code for, I would be firmly against that.

Clutch should not be allowed to be picked up and turned into a commercial product, and we want to see any and all improvements shared here. The licenses AGPL and similar (GPL) are to encourage that.

If you want to use Clutch in your project, use it in binary form. Should you distribute your product, you still must release Clutch code including any and all changes you have made. Those are the licensing terms. The Affero license also covers if you decide to try and hide the code behind a server. Legally you are required to release it in that case too.

**Comment by NinjaLikesCheez** [comment]
In order to do any license change you'd need to convince most of the code contributors that it's in their interest to do so.

Some reasoning behind why you require the change would help. We'd then need most of the code contributors to agree and be willing to change it (I believe this is the case, should contributors want to go forward with this I'd look more into how to do it). 

Personally I like AGPL.
